FROM node:22-alpine

WORKDIR /app

COPY ../frontend/package.json ../frontend/package-lock.json ./
RUN npm ci

COPY ../frontend .
RUN npm run build

FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html
EXPOSE 80
